site_name: XMC Docs
theme: readthedocs
pages:
  - Home: index.md
  - Cmdlets:
    - Add-XmcEndSystemToGroup: cmdlets/Add-XmcEndSystemToGroup.md
    - Connect-XmcServer: cmdlets/Connect-XmcServer.md
    - Get-XmcEndSystem: cmdlets/Get-XmcEndSystem.md
    - Get-XmcEndSystemGroup: cmdlets/Get-XmcEndSystemGroup.md
    - New-XmcEndSystem: cmdlets/New-XmcEndSystem.md
    - New-XmcEndSystemGroup: cmdlets/New-XmcEndSystemGroup.md
    - New-XmcServer: cmdlets/New-XmcServer.md